### ISSUE TITLE
Ajax send like

### ISSUE THREAD

**Issue by vjandrei** [levidurfee/CraftyLove#11]
Hi, great plugin.
For the user it would be great that when you like the like it will send it by ajax and dont load the page after send.

**Comment by levidurfee** [comment]
Hey @vjandrei ! Thanks :)

I'll work on adding that as a feature.

**Comment by levidurfee** [comment]
@vjandrei have you tried implementing this with ajax?

[Call plugin controller from frontend with ajax](http://craftcms.stackexchange.com/questions/11867/call-plugin-controller-from-frontend-with-ajax)
[Controllers](https://craftcms.com/docs/plugins/controllers)

**Comment by vjandrei** [comment]
@levidurfee not yet, I will try that.
